FROM node:20-alpine

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código
COPY . .

# Exponer puerto
EXPOSE 5173

# Comando para desarrollo (hot reload)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
