server:
  port: 8081

spring:
  application:
    name: ms-auth
  config:
    import: "optional:configserver:http://ds-config:8888"
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/db_auth
    username: ${DB_USER:dsadmin}
    password: ${DB_PASS:dspass2026}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:driving-school-jwt-secret-key-minimum-512-bits-for-hs512-algorithm-2026-extended}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info