server:
  port: 8083

spring:
  application:
    name: ms-instructores
  datasource:
    url: jdbc:postgresql://${DB_HOST:ds-postgres}:${DB_PORT:5432}/db_instructores
    username: ${DB_USER:dsadmin}
    password: ${DB_PASS:dspass2026}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    